## dummy commit 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: appbundle-project-dev
  syncPolicy:
    automated: {} 
  source:
    path: argocd/apps-children/dev
    repoURL: https://github.com/shamonshan/argocd-root
    targetRevision: HEAD
