repos:  
    - name: fc
      namespace: https://github.com/shamonshan/argocd-demo-deployment.git
      commitHash: HEAD
    - name: wl
      namespace: https://github.com/shamonshan/argocd-demo-deployment-1.git
      commitHash: HEAD