config:
 repos:  
    - url: https://github.com/shamonshan/argocd-demo-deployment.git
      application: fc
      version: HEAD
    - url: https://github.com/shamonshan/argocd-demo-deployment-1.git
      application: wl
      version: HEAD