apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy: {}
  project: appbundle-project-dev
  source:
    path: helm
    repoURL: https://github.com/shamonshan/argocd-demo-deployment.git
    targetRevision: HEAD
   
