apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-and-union-in-matrix
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - union:
              mergeKeys:
                - cluster
              generators:
                - list:
                    elements:
                      - cluster: engineering-dev
                        url: https://kubernetes.default.svc
                        values:
                          project: default
                      - cluster: engineering-prod
                        url: https://kubernetes.default.svc
                        values:
                          project: default
                - list:
                    elements:
                      - cluster: engineering-dev
                        url: https://kubernetes.default.svc
                        values:
                          project: default
                      - cluster: engineering-test
                        url: https://kubernetes.default.svc
                        values:
                          project: default
          - matrix:
              generators:
                - list:
                    elements:
                      - values:
                          suffix: '1'
                      - values:
                          suffix: '2'
                - list:
                    elements:
                      - values:
                          prefix: 'first'
                      - values:
                          prefix: 'second'
  template:
    metadata:
      name: '{{.values.prefix}}-{{.cluster}}-{{.values.suffix}}'
    spec:
      project: '{{.values.project}}'
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.path.basename}}'