apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-cli
  namespace: default
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test
  sources:
  - repoURL: 'https://github.com/shamonshan/argocd-demo-deployment-1.git'
    path: helm
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/configs/values.yaml
  - repoURL: 'https://github.com/shamonshan/helm-configs.git'
    targetRevision: HEAD
    ref: values